import { createContext, useContext, useState, useEffect, ReactNode } from "react";

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'app.title': 'FarcastAI',
    'app.subtitle': 'AI Content Creator',
    'header.theme': 'Theme',
    'header.shop': 'Shop', 
    'header.about': 'About',
    'header.language': 'Language',
    'wallet.connect': 'Connect Wallet',
    'wallet.connecting': 'Connecting...',
    'wallet.connected': 'Wallet Connected',
    'wallet.disconnect': 'Disconnect',
    'wallet.viewProfile': 'View Profile',
    'wallet.copyAddress': 'Copy Address',
    'wallet.ensName': 'ENS Name',
    'wallet.address': 'Wallet Address',
    'wallet.balance': 'Balance',
    'wallet.connectWithFarcaster': 'Connect with Farcaster',
    'wallet.connectWithCoinbase': 'Connect with Coinbase Wallet',
    'wallet.farcasterDescription': 'Use your Farcaster identity',
    'wallet.coinbaseDescription': 'Use Coinbase Wallet app',
    'wallet.chooseWallet': 'Choose a wallet to connect and access the FarcastAI platform',
    'wallet.farcasterConnected': 'Farcaster Wallet',
    'wallet.farcasterConnectedDesc': 'Connected with Farcaster wallet',
    'wallet.coinbaseConnected': 'Coinbase Wallet',
    'wallet.coinbaseConnectedDesc': 'Connected with Coinbase wallet',
    'wallet.connectionFailed': 'Connection Failed',
    'wallet.connectionFailedDesc': 'Please make sure you have a Web3 wallet installed and try again',
    'wallet.coinbaseFailedDesc': 'Please make sure you have Coinbase Wallet installed and try again',
    'wallet.disconnected': 'Wallet Disconnected',
    'wallet.disconnectedDesc': 'Your wallet has been disconnected',
    'wallet.unknown': 'Unknown',
    'wallet.connectYourWallet': 'Connect Your Wallet',
    'wallet.chooseWalletToConnect': 'Choose a wallet to connect and access the FarcastAI platform',
    'wallet.farcaster': 'Farcaster',
    'wallet.connectWallet': 'Connect wallet',
    'wallet.coinbaseWallet': 'Coinbase Wallet',
    'wallet.connectUsingCoinbase': 'Connect using Coinbase Wallet',
    'wallet.termsOfService': 'By connecting your wallet, you agree to our Terms of Service',
    'wallet.aiContentRequiresWallet': 'AI Content Requires Wallet',
    'wallet.connectWalletToCastAI': 'Please connect your wallet to cast AI-generated content',
    'wallet.farcasterLinked': 'Farcaster Account Linked',
    'wallet.farcasterLinkedDesc': '@{username} account has been automatically linked',
    'wallet.displayName': 'Display Name',
    'wallet.username': 'Username',
    'wallet.farcasterID': 'Farcaster ID',
    'content.generate': 'Generate Content',
    'content.preparing': 'Preparing...',
    'content.prepare': 'Prepare Cast',
    'content.openFarcaster': 'Open in Farcaster',
    'content.close': 'Close',
    'content.readyToPost': 'Cast ready! Share manually on Farcaster',
    'content.topic': 'Topic',
    'content.topicPlaceholder': 'What would you like to create content about?',
    'content.contentType': 'Content Type',
    'content.tone': 'Tone',
    'content.suggestions.title': 'Quick Suggestions',
    'content.suggestions.dailyQuote': 'Daily Quote',
    'content.suggestions.baseToken': 'Base Token',
    'content.suggestions.farcasterInfo': 'What is Farcaster?',
    'content.suggestions.cryptoNews': 'Crypto News',
    'content.suggestions.defiTrends': 'DeFi Trends',
    'content.suggestions.aiTech': 'AI Technology',
    'content.suggestions.nftTrends': 'NFT Trends',
    'content.suggestions.web3Gaming': 'Web3 Gaming',
    'content.generator': 'Content Generator',
    'content.aiGeneration': 'AI Generation',
    'content.manualInput': 'Manual Input',
    'content.yourContent': 'Your Content',
    'content.manualInput.placeholder': 'Write your content here...\n\nYou can create:\n• Thread posts with numbered points (1/, 2/, 3/)\n• News updates and analysis\n• Personal stories and experiences\n• Educational content\n• Creative writing\n\nTip: Use emojis and line breaks for better readability!',
    'content.topic.placeholder': 'What would you like to create content about?',
    'content.type': 'Content Type',
    'content.edit': 'Edit',
    'content.save': 'Save',
    'content.cancel': 'Cancel',
    'content.characters': 'characters',
    'content.readyToUse': 'Ready to use',
    'content.useThisContent': 'Use This Content',
    'content.preview': 'Content Preview',
    'content.saveChanges': 'Save Changes',
    'content.prepareCast': 'Prepare Cast',
    'content.castPrepared': 'Cast prepared!',
    'content.shareManually': 'Share manually on Farcaster',
    'content.castOpened': 'Cast opened!',
    'content.nativeFarcasterOpened': 'Native Farcaster compose opened',
    'content.preparedContent': 'Prepared content:',
    'content.noContentToPrepare': 'No content to prepare',
    'content.generateContentFirst': 'Please generate content before preparing cast',
    'content.publishingFailed': 'Publishing failed',
    'content.failedToPublish': 'Failed to publish content to Farcaster',
    'content.contentUpdated': 'Content updated',
    'content.changesSaved': 'Your changes have been saved',
    'content.reply': 'Reply',
    'content.recast': 'Recast',
    'content.like': 'Like',
    'toast.contentGenerated': 'Content Generated',
    'toast.contentReady': 'Your AI-powered content is ready for review',
    'toast.tryAgainLater': 'Please try again later.',
    'toast.quotaExceeded': 'AI API quota exceeded',
    'toast.quotaExceededDesc': 'Please check your AI API billing or try the manual content creation mode.',
    'toast.configIssue': 'AI API configuration issue',
    'toast.configIssueDesc': 'Please check your API key configuration.',
    'toast.tooManyRequests': 'Too many requests',
    'toast.tooManyRequestsDesc': 'Please wait a moment and try again.',
    'toast.failedToGenerate': 'Failed to generate content',
    'toast.draftSaved': 'Draft saved',
    'toast.draftSavedDesc': 'Your content has been saved as a draft',
    'toast.saveFailed': 'Save failed',
    'toast.saveFailedDesc': 'Failed to save draft',
    'toast.topicRequired': 'Topic required',
    'toast.topicRequiredDesc': 'Please enter a topic for content generation',
    'toast.contentTypeRequired': 'Content type required',
    'toast.contentTypeRequiredDesc': 'Please select a content type',
    'toast.contentRequired': 'Content required',
    'toast.contentRequiredDesc': 'Please enter some content',
    'toast.contentTooShort': 'Content too short',
    'toast.contentTooShortDesc': 'Content must be at least 10 characters',
    'toast.manualContentReady': 'Content ready!',
    'toast.manualContentReadyDesc': 'Your manual content is ready for review',
    'button.saving': 'Saving...',
    'button.saveAsDraft': 'Save as Draft',
    'content.generatedContentPlaceholder': 'Generated content will appear here...',
    'content.editPlaceholder': 'Edit your content here...',
    'content.recent': 'Recent Activity',
    'content.published': 'Published',
    'content.view': 'View',
    'image.producer': 'Image Producer',
    'image.selected': 'Image Selected',
    'image.uploadedSelected': 'Uploaded image selected',
    'image.stockPhotoSelected': 'Stock photo selected',
    'image.stockPhotos': 'Stock Photos',
    'image.uploadImage': 'Upload Image',
    'image.searchStockPhotos': 'Search Stock Photos',
    'image.searchPlaceholder': 'Search for images...',
    'image.clickToUpload': 'Click to upload images',
    'image.noUploadedImages': 'No uploaded images yet',
    'image.uploadYourImages': 'Upload Your Images',
    'image.searchRequired': 'Search query required',
    'image.enterSearchTerm': 'Please enter a search term',
    'image.invalidFileType': 'Invalid file type',
    'image.uploadImageFile': 'Please upload an image file (JPG, PNG, GIF, etc.)',
    'image.fileTooLarge': 'File too large',
    'image.uploadSmaller10MB': 'Please upload an image smaller than 10MB',
    'image.imageUploaded': 'Image uploaded',
    'footer.poweredBy': 'Powered by Gemini AI & Pexels',
    'preview.yourUsername': 'Your Username',
    'preview.now': 'now',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'settings': 'Settings',
    'comingSoon': 'Coming soon...',
    'aboutDescription': 'FarcastAI - AI-powered content creation for Farcaster'
  },
  tr: {
    'app.title': 'FarcastAI',
    'app.subtitle': 'AI İçerik Üreticisi',
    'header.theme': 'Tema',
    'header.shop': 'Mağaza',
    'header.about': 'Hakkında', 
    'header.language': 'Dil',
    'wallet.connect': 'Cüzdan Bağla',
    'wallet.connecting': 'Bağlanıyor...',
    'wallet.connected': 'Cüzdan Bağlandı',
    'wallet.disconnect': 'Bağlantıyı Kes',
    'wallet.viewProfile': 'Profili Görüntüle',
    'wallet.copyAddress': 'Adresi Kopyala',
    'wallet.ensName': 'ENS Adı',
    'wallet.address': 'Cüzdan Adresi',
    'wallet.balance': 'Bakiye',
    'wallet.connectWithFarcaster': 'Farcaster ile Bağlan',
    'wallet.connectWithCoinbase': 'Coinbase Wallet ile Bağlan',
    'wallet.farcasterDescription': 'Farcaster kimliğinizi kullanın',
    'wallet.coinbaseDescription': 'Coinbase Wallet uygulamasını kullanın',
    'wallet.chooseWallet': 'FarcastAI platformuna erişmek için bir cüzdan seçin',
    'wallet.farcasterConnected': 'Farcaster Cüzdanı',
    'wallet.farcasterConnectedDesc': 'Farcaster cüzdanı ile bağlandı',
    'wallet.coinbaseConnected': 'Coinbase Cüzdanı',
    'wallet.coinbaseConnectedDesc': 'Coinbase cüzdanı ile bağlandı',
    'wallet.connectionFailed': 'Bağlantı Başarısız',
    'wallet.connectionFailedDesc': 'Lütfen Web3 cüzdanınızın yüklü olduğundan emin olun ve tekrar deneyin',
    'wallet.coinbaseFailedDesc': 'Lütfen Coinbase Wallet uygulamasının yüklü olduğundan emin olun ve tekrar deneyin',
    'wallet.disconnected': 'Cüzdan Bağlantısı Kesildi',
    'wallet.disconnectedDesc': 'Cüzdanınızın bağlantısı kesildi',
    'wallet.unknown': 'Bilinmeyen',
    'wallet.connectYourWallet': 'Cüzdanınızı Bağlayın',
    'wallet.chooseWalletToConnect': 'FarcastAI platformuna erişmek için bir cüzdan seçin',
    'wallet.farcaster': 'Farcaster',
    'wallet.connectWallet': 'Cüzdan bağla',
    'wallet.coinbaseWallet': 'Coinbase Wallet',
    'wallet.connectUsingCoinbase': 'Coinbase Wallet kullanarak bağlan',
    'wallet.termsOfService': 'Cüzdanınızı bağlayarak Hizmet Şartlarımızı kabul etmiş olursunuz',
    'wallet.aiContentRequiresWallet': 'AI İçerik Cüzdan Gerektiriyor',
    'wallet.connectWalletToCastAI': 'AI ile üretilen içeriği paylaşmak için lütfen cüzdanınızı bağlayın',
    'wallet.farcasterLinked': 'Farcaster Hesabı Bağlandı',
    'wallet.farcasterLinkedDesc': '@{username} hesabınız otomatik olarak bağlandı',
    'wallet.displayName': 'Görünen Ad',
    'wallet.username': 'Kullanıcı Adı',
    'wallet.farcasterID': 'Farcaster ID',
    'content.generate': 'İçerik Üret',
    'content.preparing': 'Hazırlanıyor...',
    'content.prepare': 'Cast Hazırla', 
    'content.openFarcaster': 'Farcaster\'da Aç',
    'content.close': 'Kapat',
    'content.readyToPost': 'Cast hazırlandı! Farcaster\'da manuel olarak paylaşın',
    'content.topic': 'Konu',
    'content.topicPlaceholder': 'Hangi konuda içerik oluşturmak istiyorsunuz?',
    'content.contentType': 'İçerik Türü',
    'content.tone': 'Ton',
    'content.suggestions.title': 'Hızlı Öneriler',
    'content.suggestions.dailyQuote': 'Günün Sözü',
    'content.suggestions.baseToken': 'Base Token',
    'content.suggestions.farcasterInfo': 'Farcaster Nedir?',
    'content.suggestions.cryptoNews': 'Kripto Haberleri',
    'content.suggestions.defiTrends': 'DeFi Trendleri',
    'content.suggestions.aiTech': 'AI Teknolojisi',
    'content.suggestions.nftTrends': 'NFT Trendleri',
    'content.suggestions.web3Gaming': 'Web3 Oyunları',
    'content.generator': 'İçerik Üreticisi',
    'content.aiGeneration': 'AI Üretimi',
    'content.manualInput': 'Manuel Giriş',
    'content.yourContent': 'İçeriğiniz',
    'content.manualInput.placeholder': 'İçeriğinizi buraya yazın...\n\nŞunları oluşturabilirsiniz:\n• Numaralı konulu gönderiler (1/, 2/, 3/)\n• Haber güncellemeleri ve analizler\n• Kişisel hikayeler ve deneyimler\n• Eğitici içerik\n• Yaratıcı yazılar\n\nİpucu: Daha iyi okunabilirlik için emoji ve satır arası kullanın!',
    'content.topic.placeholder': 'Hangi konuda içerik oluşturmak istiyorsunuz?',
    'content.type': 'İçerik Türü',
    'content.edit': 'Düzenle',
    'content.save': 'Kaydet',
    'content.cancel': 'İptal',
    'content.characters': 'karakter',
    'content.readyToUse': 'Kullanıma hazır',
    'content.useThisContent': 'Bu İçeriği Kullan',
    'content.preview': 'İçerik Önizleme',
    'content.saveChanges': 'Değişiklikleri Kaydet',
    'content.prepareCast': 'Cast Hazırla',
    'content.castPrepared': 'Cast hazırlandı!',
    'content.shareManually': 'Manuel olarak Farcaster\'da paylaşın',
    'content.castOpened': 'Cast açıldı!',
    'content.nativeFarcasterOpened': 'Native Farcaster compose açıldı',
    'content.preparedContent': 'Hazırlanan içerik:',
    'content.noContentToPrepare': 'Hazırlanacak içerik yok',
    'content.generateContentFirst': 'Lütfen cast hazırlamadan önce içerik oluşturun',
    'content.publishingFailed': 'Yayınlama başarısız',
    'content.failedToPublish': 'İçeriği Farcaster\'a yayınlama başarısız oldu',
    'content.contentUpdated': 'İçerik güncellendi',
    'content.changesSaved': 'Değişiklikleriniz kaydedildi',
    'content.reply': 'Yanıtla',
    'content.recast': 'Yeniden Yayınla',
    'content.like': 'Beğen',
    'toast.contentGenerated': 'İçerik Oluşturuldu',
    'toast.contentReady': 'AI destekli içeriğiniz inceleme için hazır',
    'toast.tryAgainLater': 'Lütfen daha sonra tekrar deneyin.',
    'toast.quotaExceeded': 'AI API kotası aşıldı',
    'toast.quotaExceededDesc': 'Lütfen AI API faturalanıznızı kontrol edin veya manuel içerik oluşturma modunu deneyin.',
    'toast.configIssue': 'AI API yapılandırma sorunu',
    'toast.configIssueDesc': 'Lütfen API anahtarı yapılandırmanızı kontrol edin.',
    'toast.tooManyRequests': 'Çok fazla istek',
    'toast.tooManyRequestsDesc': 'Lütfen bir dakika bekleyin ve tekrar deneyin.',
    'toast.failedToGenerate': 'İçerik oluşturma başarısız',
    'toast.draftSaved': 'Taslak kaydedildi',
    'toast.draftSavedDesc': 'İçeriğiniz taslak olarak kaydedildi',
    'toast.saveFailed': 'Kaydetme başarısız',
    'toast.saveFailedDesc': 'Taslak kaydedilemedi',
    'toast.topicRequired': 'Konu gerekli',
    'toast.topicRequiredDesc': 'Lütfen içerik oluşturma için bir konu girin',
    'toast.contentTypeRequired': 'İçerik türü gerekli',
    'toast.contentTypeRequiredDesc': 'Lütfen bir içerik türü seçin',
    'toast.contentRequired': 'İçerik gerekli',
    'toast.contentRequiredDesc': 'Lütfen biraz içerik girin',
    'toast.contentTooShort': 'İçerik çok kısa',
    'toast.contentTooShortDesc': 'İçerik en az 10 karakter olmalıdır',
    'toast.manualContentReady': 'İçerik hazır!',
    'toast.manualContentReadyDesc': 'Manuel içeriğiniz inceleme için hazır',
    'button.saving': 'Kaydediliyor...',
    'button.saveAsDraft': 'Taslak Olarak Kaydet',
    'content.generatedContentPlaceholder': 'Oluşturulan içerik burada görünecek...',
    'content.editPlaceholder': 'İçeriğinizi buraya düzenleyin...',
    'content.recent': 'Son Aktiviteler',
    'content.published': 'Yayınlandı',
    'content.view': 'Görüntüle',
    'image.producer': 'Resim Üreticisi',
    'image.selected': 'Resim Seçildi',
    'image.uploadedSelected': 'Yüklenen resim seçildi',
    'image.stockPhotoSelected': 'Stok fotoğraf seçildi',
    'image.stockPhotos': 'Stok Fotoğraflar',
    'image.uploadImage': 'Resim Yükle',
    'image.searchStockPhotos': 'Stok Fotoğraf Ara',
    'image.searchPlaceholder': 'Resim ara...',
    'image.clickToUpload': 'Resimleri yüklemek için tıklayın',
    'image.noUploadedImages': 'Henüz yüklenmiş resim yok',
    'image.uploadYourImages': 'Resimlerinizi Yükleyin',
    'image.searchRequired': 'Arama sorgusu gerekli',
    'image.enterSearchTerm': 'Lütfen bir arama terimi girin',
    'image.invalidFileType': 'Geçersiz dosya türü',
    'image.uploadImageFile': 'Lütfen bir resim dosyası yükleyin (JPG, PNG, GIF, vb.)',
    'image.fileTooLarge': 'Dosya çok büyük',
    'image.uploadSmaller10MB': 'Lütfen 10MB\'dan küçük bir resim yükleyin',
    'image.imageUploaded': 'Resim yüklendi',
    'footer.poweredBy': 'Gemini AI ve Pexels tarafından desteklenmektedir',
    'preview.yourUsername': 'Kullanıcı Adınız',
    'preview.now': 'şimdi',
    'theme.light': 'Açık',
    'theme.dark': 'Koyu',
    'settings': 'Ayarlar',
    'comingSoon': 'Yakında...',
    'aboutDescription': 'FarcastAI - Farcaster için AI destekli içerik oluşturma'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<string>(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('farcastai-language') || 'en';
    }
    return 'en';
  });

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('farcastai-language', lang);
    }
  };

  const t = (key: string): string => {
    const translation = translations[language as keyof typeof translations];
    return translation?.[key as keyof typeof translation] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}